using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Media.Imaging;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using ImageGenDotNet.Utilities;

namespace ImageGenDotNet.ViewModels
{
    /// <summary>
    /// Main ViewModel for the Image Generator application
    /// </summary>
    public partial class MainViewModel : ObservableObject
    {
        [ObservableProperty]
        private string _selectedModel = "fal-ai/flux-pro/v1.1";

        partial void OnSelectedModelChanged(string value)
        {
            // Cancel any pending auto-generation when model changes
            lock (_generationLock)
            {
                _autoGenerateTimer?.Dispose();
                _currentGenerationCancellation?.Cancel();
            }

            // If auto-generate is enabled and the new model supports it, schedule generation
            if (AutoGenerate && ShouldAutoGenerate())
            {
                ScheduleAutoGeneration();
            }
        }

        [ObservableProperty]
        private string _promptText = "";

        partial void OnPromptTextChanged(string value)
        {
            // Trigger auto-generation if enabled
            if (AutoGenerate && ShouldAutoGenerate())
            {
                ScheduleAutoGeneration();
            }
        }

        [ObservableProperty]
        private BitmapImage? _generatedImage;

        [ObservableProperty]
        private bool _isGenerating = false;

        [ObservableProperty]
        private string _statusText = "Ready";

        [ObservableProperty]
        private string _currentOperationText = "";

        [ObservableProperty]
        private string _detailedStatusText = "";

        [ObservableProperty]
        private bool _autoGenerate = false;

        partial void OnAutoGenerateChanged(bool value)
        {
            if (value)
            {
                // Auto-generate was enabled, schedule generation if conditions are met
                if (ShouldAutoGenerate())
                {
                    ScheduleAutoGeneration();
                }
            }
            else
            {
                // Auto-generate was disabled, cancel any pending generation
                lock (_generationLock)
                {
                    _autoGenerateTimer?.Dispose();
                    _currentGenerationCancellation?.Cancel();
                }
            }
        }

        [ObservableProperty]
        private bool _autoGenerateAfterEnhance = false;

        private readonly ImageGenerator _imageGenerator;
        private readonly PromptEnhancer _promptEnhancer;
        private readonly FileHelper _fileHelper;

        // Auto-generation fields
        private Timer? _autoGenerateTimer;
        private CancellationTokenSource? _currentGenerationCancellation;
        private readonly object _generationLock = new object();
        private const int AutoGenerateDelayMs = 2000; // 2 second delay for debouncing

        // Models that should not use auto-generation due to slower performance
        private static readonly HashSet<string> _slowModels = new HashSet<string>
        {
            "fal-ai/flux-pro/v1.1-ultra",
            "fal-ai/flux-pro/v1.1-ultra-finetuned",
            "fal-ai/imagen4/preview/ultra",
            "fal-ai/hidream-i1-full",
            "fal-ai/stable-diffusion-v35-large",
            "fal-ai/bytedance/seedream/v3/text-to-image"
        };

        public MainViewModel()
        {
            _imageGenerator = new ImageGenerator();
            _fileHelper = new FileHelper();
            
            // Validate environment and initialize components accordingly
            var validationResult = EnvironmentValidator.ValidateEnvironment();
            
            // Initialize PromptEnhancer with error handling for missing API key
            try
            {
                _promptEnhancer = new PromptEnhancer();
            }
            catch (InvalidOperationException)
            {
                _promptEnhancer = null!; // Will be handled in command CanExecute methods
            }
            
            // Set initial status based on environment validation
            if (validationResult.Warnings.Count > 0)
            {
                StatusText = "Ready - Some features may be limited (check startup messages)";
            }
            else
            {
                StatusText = "Ready - All features available";
            }
        }

        #region Properties

        public List<string> AvailableModels => _imageGenerator.GetAvailableModels();

        #endregion

        #region Auto-Generation Methods

        /// <summary>
        /// Determines if auto-generation should be triggered based on current conditions
        /// </summary>
        private bool ShouldAutoGenerate()
        {
            // Don't auto-generate if:
            // - Currently generating
            // - Prompt is empty or whitespace
            // - Selected model is in the slow models list
            return !IsGenerating && 
                   !string.IsNullOrWhiteSpace(PromptText) && 
                   !_slowModels.Contains(SelectedModel);
        }

        /// <summary>
        /// Schedules auto-generation with debouncing to avoid excessive API calls
        /// </summary>
        private void ScheduleAutoGeneration()
        {
            lock (_generationLock)
            {
                // Cancel existing timer if running
                _autoGenerateTimer?.Dispose();

                // Create new timer that will trigger auto-generation after delay
                _autoGenerateTimer = new Timer(async _ => await TriggerAutoGeneration(), 
                    null, AutoGenerateDelayMs, Timeout.Infinite);
            }
        }

        /// <summary>
        /// Triggers auto-generation if conditions are still met
        /// </summary>
        private async Task TriggerAutoGeneration()
        {
            // Double-check conditions are still valid
            if (!AutoGenerate || !ShouldAutoGenerate())
                return;

            lock (_generationLock)
            {
                // Cancel any existing generation
                _currentGenerationCancellation?.Cancel();
                _currentGenerationCancellation = new CancellationTokenSource();
            }

            try
            {
                await GenerateImageWithCancellation(_currentGenerationCancellation.Token);
            }
            catch (OperationCanceledException)
            {
                // Generation was cancelled, this is expected
            }
            catch (Exception ex)
            {
                // Handle other errors silently for auto-generation
                StatusText = $"Auto-generation failed: {ex.Message}";
            }
        }

        /// <summary>
        /// Generates an image with cancellation support for auto-generation
        /// </summary>
        private async Task GenerateImageWithCancellation(CancellationToken cancellationToken)
        {
            try
            {
                IsGenerating = true;
                UpdateOperationStatus("Auto-generating image...", $"Using model: {SelectedModel}", "Processing prompt changes...");

                // Add a small delay to show the status update
                await Task.Delay(100, cancellationToken);
                UpdateOperationStatus("Auto-generating image...", $"Using model: {SelectedModel}", "Sending request to AI service...");

                var image = await _imageGenerator.GenerateAsync(SelectedModel, PromptText);
                
                // Check if cancelled before updating UI
                cancellationToken.ThrowIfCancellationRequested();
                
                UpdateOperationStatus("", "", "");
                GeneratedImage = image;
                StatusText = "Image auto-generated successfully";
            }
            finally
            {
                IsGenerating = false;
            }
        }

        #endregion

        #region Helper Methods

        /// <summary>
        /// Updates the operation status with detailed feedback
        /// </summary>
        private void UpdateOperationStatus(string operationText, string detailedText, string statusText)
        {
            CurrentOperationText = operationText;
            DetailedStatusText = detailedText;
            if (!string.IsNullOrEmpty(statusText))
            {
                StatusText = statusText;
            }
        }

        #endregion

        #region Commands

        [RelayCommand(CanExecute = nameof(CanExecuteGenerateImage))]
        private async Task GenerateImageAsync()
        {
            // Cancel any auto-generation in progress
            lock (_generationLock)
            {
                _currentGenerationCancellation?.Cancel();
                _autoGenerateTimer?.Dispose();
            }

            try
            {
                IsGenerating = true;
                UpdateOperationStatus("Generating image...", $"Using model: {SelectedModel}", "Preparing request...");

                // Add a small delay to show the status update
                await Task.Delay(100);
                UpdateOperationStatus("Generating image...", $"Using model: {SelectedModel}", "Sending request to AI service...");

                var image = await _imageGenerator.GenerateAsync(SelectedModel, PromptText);
                
                UpdateOperationStatus("", "", "");
                GeneratedImage = image;
                StatusText = "Image generated successfully";
            }
            catch (Exception ex)
            {
                UpdateOperationStatus("", "", "");
                StatusText = $"Error generating image: {ex.Message}";
                MessageBox.Show($"Failed to generate image: {ex.Message}", "Error", 
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                IsGenerating = false;
            }
        }

        private bool CanExecuteGenerateImage()
        {
            return !IsGenerating && !string.IsNullOrWhiteSpace(PromptText);
        }

        [RelayCommand(CanExecute = nameof(CanExecuteEnhancePrompt))]
        private async Task EnhancePromptAsync()
        {
            if (_promptEnhancer == null)
            {
                var validationResult = EnvironmentValidator.ValidateEnvironment();
                var message = "Prompt enhancement is not available.\n\n" +
                            "Setup Instructions:\n" + validationResult.SetupInstructions;
                
                MessageBox.Show(message, "API Key Configuration Required", 
                    MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            try
            {
                IsGenerating = true;
                UpdateOperationStatus("Enhancing prompt...", "Using OpenAI GPT", "Analyzing your prompt...");

                var originalPrompt = PromptText;
                
                // Add a small delay to show the status update
                await Task.Delay(100);
                UpdateOperationStatus("Enhancing prompt...", "Using OpenAI GPT", "Generating enhanced version...");
                
                var enhancedPrompt = await _promptEnhancer.EnhanceAsync(originalPrompt);
                
                UpdateOperationStatus("", "", "");
                PromptText = enhancedPrompt;
                StatusText = "Prompt enhanced successfully";

                // Auto-generate if enabled
                if (AutoGenerateAfterEnhance && CanExecuteGenerateImage())
                {
                    await GenerateImageAsync();
                }
            }
            catch (Exception ex)
            {
                UpdateOperationStatus("", "", "");
                StatusText = $"Error enhancing prompt: {ex.Message}";
                MessageBox.Show($"Failed to enhance prompt: {ex.Message}", "Error", 
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                IsGenerating = false;
            }
        }

        private bool CanExecuteEnhancePrompt()
        {
            return !IsGenerating && !string.IsNullOrWhiteSpace(PromptText) && _promptEnhancer != null;
        }

        [RelayCommand(CanExecute = nameof(CanExecuteEnhancePromptWithDirections))]
        private async Task EnhancePromptWithDirectionsAsync()
        {
            if (_promptEnhancer == null)
            {
                var validationResult = EnvironmentValidator.ValidateEnvironment();
                var message = "Prompt enhancement is not available.\n\n" +
                            "Setup Instructions:\n" + validationResult.SetupInstructions;
                
                MessageBox.Show(message, "API Key Configuration Required", 
                    MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            try
            {
                // Show input dialog for directions
                var directions = InputDialog.ShowDialog(
                    "Enhancement Directions", 
                    "Enter specific directions for how to enhance the prompt:",
                    "");

                if (string.IsNullOrWhiteSpace(directions))
                {
                    StatusText = "Enhancement cancelled";
                    return;
                }

                IsGenerating = true;
                UpdateOperationStatus("Enhancing prompt...", "Using OpenAI GPT with custom directions", "Processing your directions...");

                var originalPrompt = PromptText;
                
                // Add a small delay to show the status update
                await Task.Delay(100);
                UpdateOperationStatus("Enhancing prompt...", "Using OpenAI GPT with custom directions", "Applying enhancement rules...");
                
                var enhancedPrompt = await _promptEnhancer.EnhanceAsync(originalPrompt, directions);
                
                UpdateOperationStatus("", "", "");
                PromptText = enhancedPrompt;
                StatusText = "Prompt enhanced with directions successfully";

                // Auto-generate if enabled
                if (AutoGenerateAfterEnhance && CanExecuteGenerateImage())
                {
                    await GenerateImageAsync();
                }
            }
            catch (Exception ex)
            {
                UpdateOperationStatus("", "", "");
                StatusText = $"Error enhancing prompt: {ex.Message}";
                MessageBox.Show($"Failed to enhance prompt with directions: {ex.Message}", "Error", 
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                IsGenerating = false;
            }
        }

        private bool CanExecuteEnhancePromptWithDirections()
        {
            return !IsGenerating && !string.IsNullOrWhiteSpace(PromptText) && _promptEnhancer != null;
        }

        [RelayCommand(CanExecute = nameof(CanExecuteSaveImage))]
        private async Task SaveImageAsync()
        {
            if (GeneratedImage == null)
            {
                MessageBox.Show("No image to save. Please generate an image first.", "No Image", 
                    MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            try
            {
                StatusText = "Opening save dialog...";

                var filePath = _fileHelper.ShowSaveDialog();
                if (string.IsNullOrEmpty(filePath))
                {
                    StatusText = "Save cancelled";
                    return;
                }

                StatusText = "Saving image...";
                var success = await _fileHelper.SaveImageAsync(GeneratedImage, filePath);
                if (success)
                {
                    StatusText = $"Image saved successfully to: {System.IO.Path.GetFileName(filePath)}";
                    MessageBox.Show($"Image saved successfully to:\n{filePath}", "Save Complete", 
                        MessageBoxButton.OK, MessageBoxImage.Information);
                }
                else
                {
                    StatusText = "Failed to save image";
                    MessageBox.Show("Failed to save image. Please try again.", "Save Failed", 
                        MessageBoxButton.OK, MessageBoxImage.Error);
                }
            }
            catch (Exception ex)
            {
                StatusText = $"Error saving image: {ex.Message}";
                MessageBox.Show($"Failed to save image: {ex.Message}", "Error", 
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private bool CanExecuteSaveImage()
        {
            return GeneratedImage != null && !IsGenerating;
        }

        [RelayCommand]
        private void ShowEnvironmentStatus()
        {
            var validationResult = EnvironmentValidator.ValidateEnvironment();
            var status = EnvironmentValidator.GetEnvironmentStatus();
            
            var message = "Environment Configuration Status:\n\n" + status;
            
            if (!validationResult.IsValid || validationResult.MissingKeys.Count > 0 || validationResult.InvalidKeys.Count > 0)
            {
                message += "\n\nSetup Instructions:\n" + validationResult.SetupInstructions;
            }
            
            var icon = validationResult.IsValid && validationResult.MissingKeys.Count == 0 && validationResult.InvalidKeys.Count == 0 
                ? MessageBoxImage.Information 
                : MessageBoxImage.Warning;
            
            MessageBox.Show(message, "Environment Status", MessageBoxButton.OK, icon);
        }

        #endregion

        #region Disposal

        /// <summary>
        /// Disposes of resources used by the ViewModel
        /// </summary>
        public void Dispose()
        {
            lock (_generationLock)
            {
                _autoGenerateTimer?.Dispose();
                _currentGenerationCancellation?.Cancel();
                _currentGenerationCancellation?.Dispose();
            }
        }

        #endregion

    }
}